Getting Started with Tensors


In [2]:
#import pytorch
from __future__ import print_function
import torch

An uninitialized matrix is declared, but does not contain definite known values before it is used. When an uninitialized matrix is created, whatever values were in the allocated memory at the time will appear as the initial values

In [29]:
x = torch.empty(5,3)
print(x)

tensor([[-3.8590e+14,  4.5771e-41, -3.8590e+14],
        [ 4.5771e-41,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


In [35]:
#matrx with random values
x = torch.rand(5,3)
print (x)

tensor([[0.7437, 0.3533, 0.1416],
        [0.7468, 0.6155, 0.1000],
        [0.3378, 0.3606, 0.1788],
        [0.8633, 0.5751, 0.7364],
        [0.8682, 0.6716, 0.6895]])


In [30]:
x = torch.zeros(5,3, dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [32]:
x = torch.tensor([5.5,3])
print (x)

tensor([5.5000, 3.0000])


In [37]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))

In [38]:
torch.version.cuda`

'10.1'

In [39]:
torch.cuda.current_device()

AssertionError: 
The NVIDIA driver on your system is too old (found version 10000).
Please update your GPU driver by downloading and installing a new
version from the URL: http://www.nvidia.com/Download/index.aspx
Alternatively, go to: https://pytorch.org to install
a PyTorch version that has been compiled with your version
of the CUDA driver.